---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  CloudFormation template to create an S3 bucket (optional),
  an IAM user with keys, and an IAM role for accessing the
  bucket with optional IP restriction.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: S3 Configuration
        Parameters:
          - CreateBucket
          - BucketName
      - Label: IAM Configuration
        Parameters:
          - UserName
          - EnableIPRestriction
          - AllowedIPRange
    ParameterLabels:
      CreateBucket:
        default: Create New S3 Bucket?
      BucketName:
        default: S3 Bucket Name
      UserName:
        default: IAM User Name
      EnableIPRestriction:
        default: Enable IP Restriction?
      AllowedIPRange:
        default: Allowed IP Range (CIDR)

Parameters:
  CreateBucket:
    Type: String
    Description: Whether to create a new S3 bucket.
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
  BucketName:
    Type: String
    Description: Name of the S3 bucket. Leave empty to auto-generate.
  UserName:
    Type: String
    Description: Name of the IAM user to create. Leave empty to auto-generate.
    AllowedPattern: "^[a-zA-Z0-9-_]*$"
    MaxLength: 64
  EnableIPRestriction:
    Type: String
    Description: Enable IP restriction for the IAM role.
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
  AllowedIPRange:
    Type: String
    Description: >
      Allowed IP range in CIDR notation (e.g., 192.168.1.0/24).
      Required if IP restriction is enabled.
    Default: "0.0.0.0/0"
    ConstraintDescription: Must be a valid CIDR block.

Conditions:
  CreateNewBucket: !Equals [!Ref CreateBucket, "true"]
  DynamicBucketName: !Equals [!Ref BucketName, ""]
  DynamicUserName: !Equals [!Ref UserName, ""]
  RestrictIP: !Equals [!Ref EnableIPRestriction, "true"]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateNewBucket
    Properties:
      BucketName: !If [DynamicBucketName, !Ref "AWS::NoValue", !Ref BucketName]
      VersioningConfiguration:
        Status: Enabled
      # https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html
      LifecycleConfiguration:
        Rules:
          # For the deletion to occur, both the <NoncurrentDays> and
          # the <NewerNoncurrentVersions> values must be exceeded
          - Id: RetainVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 2
              NewerNoncurrentVersions: 3
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !If [DynamicUserName, !Ref "AWS::NoValue", !Ref UserName]

  IAMAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser

  IAMUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AssumeRolePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource: !GetAtt IAMRole.Arn
      Users:
        - !Ref IAMUser

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt IAMUser.Arn
            Action:
              - sts:AssumeRole
            Condition:
              Fn::If:
                - RestrictIP
                - IpAddress:
                    aws:SourceIp: !Ref AllowedIPRange
                - !Ref "AWS::NoValue"
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject*
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket*
                Resource:
                  - !If [CreateNewBucket, !Sub "arn:aws:s3:::${S3Bucket}", !Sub "arn:aws:s3:::${BucketName}"]
                  - !If [CreateNewBucket, !Sub "arn:aws:s3:::${S3Bucket}/*", !Sub "arn:aws:s3:::${BucketName}/*"]

Outputs:
  BucketName:
    Description: Name of the S3 bucket.
    Value: !If [CreateNewBucket, !Ref S3Bucket, !Ref BucketName]

  IAMUserName:
    Description: Name of the IAM user.
    Value: !Ref IAMUser

  IAMRoleArn:
    Description: ARN of the IAM role.
    Value: !GetAtt IAMRole.Arn

  AccessKeyId:
    Description: IAM User Access Key ID.
    Value: !Ref IAMAccessKey

  SecretAccessKey:
    Description: IAM User Secret Access Key.
    Value: !GetAtt IAMAccessKey.SecretAccessKey
