---
name: Development

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install pipenv
        run: |
          pip install pipenv
          pipenv requirements > requirements.txt

      - name: Determine docker tag
        id: docker_tag
        run: |
          echo "tag=dev" >> $GITHUB_OUTPUT
          echo "version=dev-$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Login to github packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cupcake-s3:develop
            ghcr.io/${{ github.repository_owner }}/cupcake-s3:${{ steps.docker_tag.outputs.version }}
